apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: kube-slack
  namespace: kube-system
spec:
  replicas: 1
  revisionHistoryLimit: 1
  template:
    metadata:
      annotations:
        schedules.alpha.kubernetes.io/critical-pod: ""
      name: kube-slack
      labels:
        app: kube-slack
    spec:
      containers:
      - name: kube-slack
        image: willwill/kube-slack:v3.3.0
        env:
        - name: SLACK_URL
          value: https://hooks.slack.com/services/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
        resources:
          requests:
            memory: 30M
            cpu: 5m
      tolerations:
        - effect: NoSchedule
          key: node-role.kubernetes.io/master
        - key: CriticalAddonsOnly
          operator: Exists